services:
  pg_age:
    build:
      context: .
      dockerfile: docker/backend/database/postgres/Dockerfile
      args:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
    container_name: pg_age
    env_file:
      - .env
    networks:
      - app_network
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    build:
      context: .
      dockerfile: docker/backend/api/Dockerfile
    container_name: backend
    depends_on:
      pg_age:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - POSTGRES_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@pg_age:5432/${POSTGRES_DB}
      - SECRET_KEY_JWT=${SECRET_KEY_JWT}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - REFRESH_TOKEN_EXPIRE_DAYS=${REFRESH_TOKEN_EXPIRE_DAYS}
    restart: unless-stopped
    networks:
      - app_network
    ports:
      - "8005:8005"

networks:
  app_network:
    driver: bridge

volumes:
  pg_data: