apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: pichta
data:
  POSTGRES_HOST: "{{ POSTGRES_HOST }}"
  POSTGRES_PORT: "{{ POSTGRES_PORT }}"
  BACKEND_URL: "{{ BACKEND_URL }}"
