const iconMap: { [key: string]: string } = {
    "Next.js": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nextjs/nextjs-original.svg",
    "React": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg",
    "TypeScript": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg",
    "Node.js": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg",
    "PostgreSQL": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg",
    "GraphQL": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/graphql/graphql-plain.svg",
    "Docker": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg",
    "AWS": "https://www.w3schools.com/aws/images/awslogo.png",
    "Redux": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/redux/redux-original.svg",
    "Jest": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jest/jest-plain.svg",
    "Tailwind CSS": "https://icon.icepanel.io/Technology/svg/Tailwind-CSS.svg",
    "Python": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg",
    "MongoDB": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original.svg",
    "Kubernetes": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/kubernetes/kubernetes-plain.svg",
    "Vue.js": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vuejs/vuejs-original.svg",
    "Git": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg",
    "GitHub": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/github/github-original.svg",
    "Java": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg",
    "Ruby": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/ruby/ruby-original.svg",
    "PHP": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/php/php-original.svg",
    "C++": "https://repository-images.githubusercontent.com/327470624/2d865200-6bf1-11eb-9d0e-2a488615d6ec",
    "C#": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/csharp/csharp-original.svg",
    "Swift": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/swift/swift-original.svg",
    "Go": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/go/go-original.svg",
    "Rust": "https://img.icons8.com/?size=100&id=haeAxVQEIg0F&format=png&color=000000",
    "Linux": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/linux/linux-original.svg",
    "Android": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/android/android-original.svg",
    "iOS": "https://img.icons8.com/?size=100&id=20822&format=png&color=000000",
    "Firebase": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/firebase/firebase-plain.svg",
    "AWS Lambda": "https://icons8.com/icon/Y9Kxy8Xl1id8/awslambda",
    "Azure": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/azure/azure-original.svg",
    "Terraform": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/terraform/terraform-original.svg",
    "Vim": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vim/vim-original.svg",
    "Electron": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/electron/electron-original.svg",
    "Jenkins": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jenkins/jenkins-original.svg",
    "Ansible": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/ansible/ansible-original.svg",
    "Apache": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/apache/apache-original.svg",
    "Nginx": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nginx/nginx-original.svg",
    "MySQL": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original.svg",
    "SQLite": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/sqlite/sqlite-original.svg",
    "Redis": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/redis/redis-original.svg",
    "Elasticsearch": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/elasticsearch/elasticsearch-original.svg",
    "Cloudflare": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/cloudflare/cloudflare-original.svg",
    "Figma": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/figma/figma-original.svg",
    "Slack": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/slack/slack-original.svg",
    "Trello": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/trello/trello-plain.svg",
    "Notion": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/notion/notion-original.svg",
    "Vercel": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vercel/vercel-original.svg",
    "Netlify": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/netlify/netlify-original.svg",
    "Jupyter": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jupyter/jupyter-original.svg",
    "Hadoop": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/hadoop/hadoop-original.svg",
    "Spark": "https://img.icons8.com/?size=100&id=0cRqPqlItA0E&format=png&color=000000",
    "Power BI": "https://img.icons8.com/?size=100&id=Ny0t2MYrJ70p&format=png&color=000000",
    "Tableau": "https://img.icons8.com/?size=100&id=BQJc3mm8NGYs&format=png&color=000000",
    "Salesforce": "https://img.icons8.com/?size=100&id=38804&format=png&color=000000",
    "Kotlin": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/kotlin/kotlin-original.svg",
    "Scala": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/scala/scala-original.svg",
    "MongoDB Atlas": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original.svg",
    "Solidity": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/solidity/solidity-original.svg",
    "GitLab": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/gitlab/gitlab-original.svg",
    "Bitbucket": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/bitbucket/bitbucket-original.svg",
    "Sass": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/sass/sass-original.svg",
    "Webpack": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/webpack/webpack-original.svg",
    "Parcel": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/parcel/parcel-original.svg",
    "Cassandra": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/cassandra/cassandra-original.svg",
    "RabbitMQ": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/rabbitmq/rabbitmq-original.svg",
    "Apache Kafka": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/apachekafka/apachekafka-original.svg",
    "Angular": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/angularjs/angularjs-original.svg",
    "Ember.js": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/ember/ember-original-wordmark.svg",
    "Svelte": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/svelte/svelte-original.svg",
    "Deno": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/denojs/denojs-original.svg",
    "Dart": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/dart/dart-original.svg",
    "Flutter": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/flutter/flutter-original.svg",
    "Xamarin": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/xamarin/xamarin-original.svg",
    "React Native": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg",
    "Ionic": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/ionic/ionic-original.svg",
    "Cordova": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/apache/apache-original.svg",
    "Unity": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/unity/unity-original.svg",
    "Unreal Engine": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/unrealengine/unrealengine-original.svg",
    "Godot": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/godot/godot-original.svg",
    "TensorFlow": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tensorflow/tensorflow-original.svg",
    "PyTorch": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/pytorch/pytorch-original.svg",
    "Keras": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/keras/keras-original.svg",
    "scikit-learn": "https://upload.wikimedia.org/wikipedia/commons/0/05/Scikit_learn_logo_small.svg",
    "OpenCV": "https://avatars.mds.yandex.net/i?id=6a358342ef62f22b39c0df2b0249abd1_l-5236434-images-thumbs&n=13",
    "Open CV": "https://avatars.mds.yandex.net/i?id=6a358342ef62f22b39c0df2b0249abd1_l-5236434-images-thumbs&n=13",
    "NumPy": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/numpy/numpy-original.svg",
    "Pandas": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/pandas/pandas-original.svg",
    "R": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/r/r-original.svg",
    "Julia": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/julia/julia-original.svg",
    "MATLAB": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/matlab/matlab-original.svg",
    "D3.js": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/d3js/d3js-original.svg",
    "Three.js": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/threejs/threejs-original.svg",
    "WebGL": "https://img.icons8.com/?size=100&id=68124&format=png&color=000000",
    "Babylon.js": "https://www.babylonjs.com/assets/logo.png",
    "Blender": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/blender/blender-original.svg",
    "Maya": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/maya/maya-original.svg",
    "Houdini": "https://img.icons8.com/?size=100&id=xyr0eNWJNQB0&format=png&color=000000",
    "ZBrush": "https://img.icons8.com/?size=100&id=a5u4SPM4ppkf&format=png&color=000000",
    "Substance Painter": "https://img.icons8.com/?size=100&id=pKrplEv3lofi&format=png&color=000000",
    "Photoshop": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/photoshop/photoshop-plain.svg",
    "Illustrator": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/illustrator/illustrator-plain.svg",
    "After Effects": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/aftereffects/aftereffects-original.svg",
    "Premiere Pro": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/premierepro/premierepro-plain.svg",
    "Sketch": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/sketch/sketch-original.svg",
    "InVision": "https://img.icons8.com/?size=100&id=cRGU9_-pgw3i&format=png&color=000000",
    "Zeplin": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/zeplin/zeplin-original.svg",
    "Adobe XD": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/xd/xd-plain.svg",
    "Framer": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/framer/framer-original.svg",
    "Axure": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/axure/axure-original.svg",
    "Balsamiq": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/balsamiq/balsamiq-original.svg",
    "Jira": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jira/jira-original.svg",
    "Confluence": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/confluence/confluence-original.svg",
    "Asana": "https://img.icons8.com/?size=100&id=KXLQJEcoy0Yu&format=png&color=000000",
    "Basecamp": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/basecamp/basecamp-original.svg",
    "Heroku": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/heroku/heroku-original.svg",
    "DigitalOcean": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/digitalocean/digitalocean-original.svg",
    "Google Cloud": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/googlecloud/googlecloud-original.svg",
    "Oracle Cloud": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/oracle/oracle-original.svg",
    "IBM Cloud": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/ibm/ibm-original.svg",
    "Alibaba Cloud": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/alibabacloud/alibabacloud-original.svg",
    "Vagrant": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vagrant/vagrant-original.svg",
    "Puppet": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/puppet/puppet-original.svg",
    "Chef": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/chef/chef-original.svg",
    "Prometheus": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/prometheus/prometheus-original.svg",
    "Grafana": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/grafana/grafana-original.svg",
    "Splunk": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/splunk/splunk-original.svg",
    "ELK Stack": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/elasticsearch/elasticsearch-original.svg",
    "Sentry": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/sentry/sentry-original.svg",
    "New Relic": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/newrelic/newrelic-original.svg",
    "Datadog": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/datadog/datadog-original.svg",
    "Selenium": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/selenium/selenium-original.svg",
    "Cypress": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/cypress/cypress-original.svg",
    "Postman": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postman/postman-original.svg",
    "SonarQube": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/sonarqube/sonarqube-original.svg",
    "Cucumber": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/cucumber/cucumber-plain.svg",
    "Gatling": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/gatling/gatling-plain.svg",
    "JMeter": "https://jmeter.apache.org/images/jmeter.png",
    "Blockchain": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/bitcoin/bitcoin-original.svg",
    "Ethereum": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/ethereum/ethereum-original.svg",
    "Hyperledger": "https://www.hyperledger.org/wp-content/uploads/2018/03/hyperledger_fabric_logo_color.png",
    "IPFS": "https://docs.ipfs.tech/images/ipfs-logo.svg",
    "WebAssembly": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/webassembly/webassembly-original.svg",
    "WebRTC": "https://webrtc.github.io/webrtc-org/assets/images/webrtc-logo-vert-retro-255x305.png",
    "gRPC": "https://grpc.io/img/logos/grpc-icon-color.png",
    "WebSockets": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg",
    "RxJS": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/rxjs/rxjs-original.svg",
    "Lodash": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/lodash/lodash-original.svg",
    "Babel": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/babel/babel-original.svg",
    "ESLint": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/eslint/eslint-original.svg",
    "Prettier": "https://prettier.io/icon.png",
    "Storybook": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/storybook/storybook-original.svg",
  // Frontend
  "Astro": "https://astro.build/assets/press/astro-icon-light-gradient.svg",
  "Preact": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/preact/preact-original.svg",
  "Solid.js": "https://www.solidjs.com/assets/logo.123b04bc.svg",
  "Alpine.js": "https://alpinejs.dev/alpine_long.svg",
  "Lit": "https://lit.dev/images/flame-favicon.svg",
  "Backbone.js": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/backbonejs/backbonejs-original.svg",
  "Polymer": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/polymer/polymer-original.svg",
  "Mithril": "https://mithril.js.org/logo.png",
  "Eleventy": "https://www.11ty.dev/img/logo-github.svg",
  "Gatsby": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/gatsby/gatsby-plain.svg",
  "Nuxt.js": "https://nuxt.com/icon.png",
  "Vite": "https://vitejs.dev/logo.svg",
  "Rollup": "https://rollupjs.org/favicon.png",
  "esbuild": "https://esbuild.github.io/favicon.svg",
  "Grunt": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/grunt/grunt-original.svg",
  "Gulp": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/gulp/gulp-plain.svg",
  "Less": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/less/less-plain-wordmark.svg",
  "Stylus": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/stylus/stylus-original.svg",
  
  // Backend
  "Express.js": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/express/express-original.svg",
  "Koa": "https://koajs.com/public/images/koa-logo.png",
  "Fastify": "https://www.fastify.io/images/fastify-logo-menu.d13f8da7a965c800.png",
  "NestJS": "https://nestjs.com/img/logo-small.svg",
  "Strapi": "https://strapi.io/assets/strapi-logo-light.svg",
  "Django": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/django/django-plain.svg",
  "Flask": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/flask/flask-original.svg",
  "FastAPI": "https://fastapi.tiangolo.com/img/logo-margin/logo-teal.png",
  "Spring Boot": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/spring/spring-original.svg",
  "Laravel": "https://img.icons8.com/?size=100&id=hUvxmdu7Rloj&format=png&color=000000",
  "Ruby on Rails": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/rails/rails-original-wordmark.svg",
  "ASP.NET Core": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/dotnetcore/dotnetcore-original.svg",
  "Phoenix": "https://www.phoenixframework.org/images/phoenix.png",
  "Gin": "https://raw.githubusercontent.com/gin-gonic/logo/master/color.png",
  "Echo": "https://cdn.labstack.com/images/echo-logo.svg",
  
  // DevOps
  "GitLab CI/CD": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/gitlab/gitlab-original.svg",
  "CircleCI": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/circleci/circleci-plain.svg",
  "Travis CI": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/travis/travis-plain.svg",
  "ArgoCD": "https://argo-cd.readthedocs.io/en/stable/assets/logo.png",
  "Flux": "https://fluxcd.io/img/flux-icon@2x.png",
  "Helm": "https://helm.sh/img/helm.svg",
  "Istio": "https://istio.io/latest/img/istio-whitelogo-bluebackground-framed.svg",
  "Linkerd": "https://linkerd.io/images/identity/svg/linkerd-primary-color-white-text.svg",
  "Consul": "https://www.datocms-assets.com/2885/1620155116-brandhcterraformverticalcolor.svg",
  "Vault": "https://www.datocms-assets.com/2885/1620159869-brandvaultverticalcolor.svg",
  "Packer": "https://www.datocms-assets.com/2885/1620159887-brandpackerverticalcolor.svg",
  "Nomad": "https://www.datocms-assets.com/2885/1620159890-brandnomadverticalcolor.svg",
  
  // Databases
  "MariaDB": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original.svg",
  "CockroachDB": "https://upload.wikimedia.org/wikipedia/commons/2/29/Cockroach_Labs_Logo.svg",
  "InfluxDB": "https://influxdata.github.io/branding/img/downloads/influxdata-logo--symbol--pool-alpha.png",
  "Neo4j": "https://dist.neo4j.com/wp-content/uploads/20210423072428/neo4j-logo-2020-1.svg",
  "Couchbase": "https://www.couchbase.com/wp-content/uploads/2022/08/CB-logo-R_B.svg",
  "RethinkDB": "https://rethinkdb.com/assets/images/rethinkdb.png",
  
  // Message Brokers
  "Apache Pulsar": "https://pulsar.apache.org/img/pulsar.svg",
  "NATS": "https://nats.io/img/logos/nats-horizontal-color.png",
  "ZeroMQ": "https://upload.wikimedia.org/wikipedia/commons/3/3d/Zeromq-logo.svg",
  
  // API Gateways
  "Kong": "https://konghq.com/wp-content/uploads/2018/08/kong-combination-mark-color-256px.png",
  "Tyk": "https://tyk.io/wp-content/themes/tyk/dist/img/favicons/favicon-32x32.png",
  "Ambassador": "https://www.getambassador.io/images/ambassador-logo.svg",
  
  // Serverless
  "OpenFaaS": "https://docs.openfaas.com/images/openfaas/logo.png",
  "Knative": "https://knative.dev/docs/images/logo/rgb/knative-logo-rgb.png",
  "Apache OpenWhisk": "https://openwhisk.apache.org/images/logo/apache-openwhisk-logo-only.svg",
  
  // Observability
  "Jaeger": "https://www.jaegertracing.io/img/jaeger-icon-color.png",
  "OpenTelemetry": "https://opentelemetry.io/img/logos/opentelemetry-logo-nav.png",
  "Loki": "https://grafana.com/static/img/logos/logo-loki.svg",
  
  // Security
  "OAuth 2.0": "https://oauth.net/images/oauth-2-sm.png",
  "OpenID Connect": "https://openid.net/wordpress-content/uploads/2016/05/oidc-logo-mark.png",
  "OWASP": "https://owasp.org/assets/images/logo.png",
  "Let's Encrypt": "https://letsencrypt.org/images/le-logo-standard.svg",
  
  // Version Control
  "Mercurial": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mercurial/mercurial-original.svg",
  "Perforce": "https://www.perforce.com/themes/custom/themekit/logo.svg",
  
  // AI/ML
  "Hugging Face": "https://huggingface.co/front/assets/huggingface_logo-noborder.svg",
  "spaCy": "https://spacy.io/static/social_default-1d3b50b1eba4c2b06244425ff0c49570.jpg",
  "NLTK": "https://www.nltk.org/images/nltk.png",
  "Gensim": "https://radimrehurek.com/gensim/static/images/gensim_logo_positive_complete_tb.png",
  "MLflow": "https://www.mlflow.org/docs/latest/_static/MLflow-logo-final-black.png",
  
  // Data Engineering
  "Apache Airflow": "https://airflow.apache.org/docs/apache-airflow/stable/_images/pin_large.png",
  "Apache Beam": "https://beam.apache.org/images/beam_logo_s.png",
  "dbt": "https://www.getdbt.com/ui/img/logos/dbt-logo.svg",
  "Apache Flink": "https://flink.apache.org/img/flink-header-logo.svg",
  
  // Low-Code/No-Code
  "Retool": "https://retool.com/logo-light.svg",
  "Airtable": "https://www.airtable.com/favicon.ico",
  "Bubble": "https://d1muf25xaso8hp.cloudfront.net/https%3A%2F%2Fs3.amazonaws.com%2Fappforest_uf%2Ff1626355319613x484158047569452200%2FBubble-Logo-White%2520on%2520Black.png?w=&h=&auto=compress&dpr=1&fit=max",
  "Webflow": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/webflow/webflow-original.svg",
  
  "Yandex Cloud": "https://upload.wikimedia.org/wikipedia/commons/4/40/Yandex_Cloud_logo.svg",
  "OpenAPI / Swagger": "https://plugins.jetbrains.com/files/24393/542953/icon/default.svg",
  "SQLAlchemy": "https://upload.wikimedia.org/wikipedia/commons/d/d7/SQLAlchemy.svg",
  "GitHub Actions": "https://avatars.githubusercontent.com/u/44036562?s=280&v=4",
  "Bitrix24": "https://upload.wikimedia.org/wikipedia/commons/c/ce/Bitrix24-logo-ru.svg",
  "Интеграция с 1С": "https://upload.wikimedia.org/wikipedia/commons/9/93/1C_Company_logo.svg",
  "PostGIS": "https://upload.wikimedia.org/wikipedia/commons/7/7b/Logo_square_postgis.png",
  "ClickHouse": "https://upload.wikimedia.org/wikipedia/commons/0/0b/ClickHouse_Logo_220x220.svg",
  "Статистический анализ": "https://banner2.cleanpng.com/20180330/ade/aviez2p7u.webp",
  "SSIS (SQL Server Integration Services)": "https://logodix.com/logo/823396.jpg",
  "PL/SQL": "https://i.pinimg.com/236x/69/73/81/697381b750f8245ac854dee3d63ee1b4.jpg",
  "Визуализация данных (Power BI, Tableau и др.)": "https://i.pinimg.com/736x/1d/55/50/1d55507d7d6942c57fa9efe6508da4e8.jpg",
  
  "Frontend": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Front-end-logo-color%402x.png/640px-Front-end-logo-color%402x.png",
  "Backend": "https://cdn-icons-png.flaticon.com/512/446/446680.png",
  "DevOps": "https://cdn-icons-png.flaticon.com/512/6125/6125001.png",
  "Database": "https://cdn-icons-png.flaticon.com/512/4248/4248443.png",
  "Cloud": "https://cdn-icons-png.flaticon.com/512/3305/3305673.png",
  "Mobile": "https://img.icons8.com/?size=100&id=56378&format=png&color=000000",
  "Mobile Development": "https://img.icons8.com/?size=100&id=56378&format=png&color=000000",
  "AI/ML": "https://cdn-icons-png.flaticon.com/512/2103/2103832.png",
  "Data Science": "https://cdn-icons-png.flaticon.com/512/2821/2821637.png",
  "Security": "https://cdn-icons-png.flaticon.com/512/2092/2092669.png",
  "Testing": "https://cdn-icons-png.flaticon.com/512/1205/1205526.png",
  "Game Development": "https://cdn-icons-png.flaticon.com/512/686/686589.png",
  "IoT": "https://cdn-icons-png.flaticon.com/512/6080/6080697.png",
  "AR/VR": "https://cdn-icons-png.flaticon.com/512/1208/1208168.png",
  
  "NoSQL": "https://logodix.com/logo/1960562.png",
  "SQL": "https://logodix.com/logo/542051.png",
  "CI/CD": "https://habrastorage.org/getpro/habr/upload_files/fd5/8e7/aed/fd58e7aed7c9aa1cc417ffaf2d315561.png",
  "JavaScript": "https://www.freepnglogos.com/uploads/javascript-png/javascript-vector-logo-yellow-png-transparent-javascript-vector-12.png",

  "aiohttp": "https://raw.githubusercontent.com/aio-libs/aiohttp/master/docs/aiohttp-plain.svg",
  "AsyncIO": "https://www.svgrepo.com/download/88703/api.svg",
  "Celery": "https://www.svgrepo.com/download/447056/celery.svg",
  "Tortoise ORM": "https://www.svgrepo.com/download/197976/yandex.svg",
  "Pytest": "https://upload.wikimedia.org/wikipedia/commons/b/ba/Pytest_logo.svg",
  "UnitTest": "https://www.svgrepo.com/download/88703/api.svg",
  "Mock": "https://www.svgrepo.com/download/88703/api.svg",
  "REST": "https://www.svgrepo.com/download/88703/api.svg",
  "SOAP": "https://www.svgrepo.com/download/2108/soap.svg",
  "Agile / Scrum": "https://www.svgrepo.com/download/372946/scrum.svg",
  "Лидерство и наставничество": "https://www.svgrepo.com/download/253296/leader.svg",
  "Аналитическое мышление": "https://www.svgrepo.com/download/122646/leadership.svg",
  "Английский язык — уровень B1": "https://www.svgrepo.com/download/197976/yandex.svg",
  "Коммуникабельность": "https://www.svgrepo.com/download/122646/leadership.svg",
  "Решение проблем": "https://www.svgrepo.com/download/122646/leadership.svg",
  
  "Разработка через тестирование (TDD)": "https://cdn-icons-png.flaticon.com/512/3600/3600833.png",
  "ООП (объектно-ориентированное программирование)": "https://cdn-icons-png.flaticon.com/512/1800/1800931.png",
  "Паттерны проектирования": "https://cdn-icons-png.flaticon.com/512/906/906343.png",
  "Микросервисы": "https://cdn-icons-png.flaticon.com/512/3383/3383956.png",
  "Чистая архитектура (Clean Architecture)": "https://cdn-icons-png.flaticon.com/512/1087/1087815.png",
  "GCP": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/googlecloud/googlecloud-original.svg",
  "Анализ данных": "https://cdn-icons-png.flaticon.com/512/4149/4149650.png",
  "Оптимизация запросов": "https://cdn-icons-png.flaticon.com/512/5288/5288412.png",
  "Хранимые процедуры и функции": "https://cdn-icons-png.flaticon.com/512/3819/3819697.png",
  "Oracle Database": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/oracle/oracle-original.svg",
  "Большие данные (Big Data)": "https://cdn-icons-png.flaticon.com/512/4341/4341139.png",
  "ETL-процессы": "https://cdn-icons-png.flaticon.com/512/4184/4184458.png",
  "Хранилища данных (DWH)": "https://cdn-icons-png.flaticon.com/512/3524/3524388.png",
  "Моделирование данных": "https://cdn-icons-png.flaticon.com/512/4226/4226022.png",
  "BPMN / Диаграммы потоков данных": "https://cdn-icons-png.flaticon.com/512/3208/3208726.png",
  "MS Excel (продвинутый уровень)": "https://cdn-icons-png.flaticon.com/512/732/732220.png",
  "Power Query / Power Pivot": "https://powerbi.microsoft.com/pictures/shared/social/social-default-image.png",
  "MS Office": "https://cdn-icons-png.flaticon.com/512/732/732221.png",
  "UML / ER-диаграммы": "https://cdn-icons-png.flaticon.com/512/3889/3889523.png",
  "Системы отчётности (SSRS и др.)": "https://cdn-icons-png.flaticon.com/512/4064/4064631.png",
  "Бизнес-анализ": "https://cdn-icons-png.flaticon.com/512/2972/2972369.png",
  "Математика и аналитическое мышление": "https://cdn-icons-png.flaticon.com/512/4341/4341039.png",
  "Командная работа": "https://avatars.mds.yandex.net/get-ydo/3927445/2a0000017fcfdda3a1cfb41fca8734e8b2f8/diploma",
  "Инициативность и энтузиазм": "https://static.vecteezy.com/system/resources/previews/002/212/610/non_2x/line-icon-for-ambitious-vector.jpg",
  "Английский язык — A2 или выше": "https://cdn-icons-png.flaticon.com/512/2991/2991153.png",
  ".NET Framework": "https://upload.wikimedia.org/wikipedia/commons/7/7d/Microsoft_.NET_logo.svg",
  "T-SQL (Transact-SQL)": "https://cdn-icons-png.flaticon.com/512/2721/2721275.png",
  "MS SQL Server": "https://upload.wikimedia.org/wikipedia/commons/8/87/Sql_data_base_with_logo.png",

  //  КАТЕГРИИ
  "Языки программирования": "https://cdn-icons-png.flaticon.com/512/2721/2721290.png",
  "Веб-фреймворки": "https://cdn-icons-png.flaticon.com/512/2721/2721293.png",
  "Асинхронное программирование": "https://cdn-icons-png.flaticon.com/512/1148/1148030.png",
  "Базы данных": "https://cdn-icons-png.flaticon.com/512/4248/4248443.png",
  "Инструменты DevOps": "https://cdn-icons-png.flaticon.com/512/6125/6125001.png",
  "Тестирование": "https://cdn-icons-png.flaticon.com/512/1205/1205526.png",
  "Проектирование API": "https://cdn-icons-png.flaticon.com/512/10793/10793035.png",
  "Архитектура и проектирование ПО": "https://cdn-icons-png.flaticon.com/512/4727/4727493.png",
  "Облачные платформы": "https://cdn-icons-png.flaticon.com/512/3305/3305673.png",
  "Анализ данных и инструменты": "https://cdn-icons-png.flaticon.com/512/4108/4108415.png",
  "Управление проектами": "https://clipart-library.com/8300/2368/pict--project-team-project-management---vector-stencils-library.png--diagram-flowchart-example.png",
  "Гибкие навыки (Soft Skills)": "https://cdn-icons-png.flaticon.com/512/1010/1010043.png",
  "Основные навыки SQL": "https://orageek.com/wp-content/uploads/2019/01/sql-png-5-283x300.png",
  "Базы данных и технологии": "https://avatars.mds.yandex.net/i?id=e1bd99f9c8cdade4774740514f55f1e5-2899831-images-thumbs&n=13",
  "Инженерия данных / ETL": "https://cdn-icons-png.flaticon.com/512/1183/1183708.png",
  "Программирование и скрипты": "https://yt3.googleusercontent.com/ytc/AIdro_nbPJUggk8eHSbpHNW02fKpGw6QV4ehRhUybqpZwGuYyA=s900-c-k-c0x00ffffff-no-rj",
  "Инструменты и среды": "https://cdn-icons-png.flaticon.com/512/4359/4359695.png",
  "Аналитика и отчётность": "https://proinfosoft.ru/assets/images/Consultation/Otvetstvennost-pri-otklonenii-otcheta-PEK.png",
  "Гибкие навыки (soft skills)": "https://img1.wsimg.com/isteam/ip/b3ef487a-bb7d-4838-ae40-9009930b7646/Screen%20Shot%202019-12-09%20at%2012.52.02%20AM.png",

  //  РОЛИ
  "Python-разработчик": "https://cdn-icons-png.flaticon.com/512/919/919852.png",
  "SQL-разработчик": "https://cdn-icons-png.flaticon.com/512/603/603201.png",
  "Frontend-разработчик": "https://cdn-icons-png.flaticon.com/512/1055/1055687.png",
  "Backend-разработчик": "https://cdn-icons-png.flaticon.com/512/2721/2721302.png",
  "DevOps-инженер": "https://cdn-icons-png.flaticon.com/512/4213/4213443.png",
  "Data Scientist": "https://cdn-icons-png.flaticon.com/512/4659/4659085.png",
  "Менеджер проектов": "https://cdn-icons-png.flaticon.com/512/1159/1159633.png",
  "Аналитик данных": "https://cdn-icons-png.flaticon.com/512/4341/4341139.png",
  "Инженер по тестированию": "https://cdn-icons-png.flaticon.com/512/4248/4248441.png",
  "ML-инженер": "https://cdn-icons-png.flaticon.com/512/3039/3039435.png",
  "Администратор баз данных": "https://cdn-icons-png.flaticon.com/512/4320/4320336.png",
  "Инженер данных": "https://cdn-icons-png.flaticon.com/512/6134/6134064.png",

  ".net core": "https://upload.wikimedia.org/wikipedia/commons/e/ee/.NET_Core_Logo.svg",
  "1C Developer": "https://upload.wikimedia.org/wikipedia/commons/9/93/1C_Company_logo.svg",
  "1C ERP": "https://upload.wikimedia.org/wikipedia/commons/9/93/1C_Company_logo.svg",
  "1C Products": "https://upload.wikimedia.org/wikipedia/commons/9/93/1C_Company_logo.svg",
  "1C: Бухгалтерия": "https://upload.wikimedia.org/wikipedia/commons/9/93/1C_Company_logo.svg",
  "1C: Предприятие": "https://upload.wikimedia.org/wikipedia/commons/9/93/1C_Company_logo.svg",
  "1С ЕРП": "https://upload.wikimedia.org/wikipedia/commons/9/93/1C_Company_logo.svg",
  "1С УТ": "https://upload.wikimedia.org/wikipedia/commons/9/93/1C_Company_logo.svg",
  "1С программирование": "https://upload.wikimedia.org/wikipedia/commons/9/93/1C_Company_logo.svg",
  "1С-Битрикс": "https://upload.wikimedia.org/wikipedia/commons/1/1c/Bitrix_Logo.png",
  "1С: Документооборот": "https://upload.wikimedia.org/wikipedia/commons/9/93/1C_Company_logo.svg",
  "1С: Зарплата и управление персоналом": "https://upload.wikimedia.org/wikipedia/commons/9/93/1C_Company_logo.svg",
  "1С: Предприятие 8": "https://upload.wikimedia.org/wikipedia/commons/9/93/1C_Company_logo.svg",
  "1С: Розница": "https://upload.wikimedia.org/wikipedia/commons/9/93/1C_Company_logo.svg",
  "1С: Торговля": "https://upload.wikimedia.org/wikipedia/commons/9/93/1C_Company_logo.svg",
  "1С: Управление Торговлей": "https://upload.wikimedia.org/wikipedia/commons/9/93/1C_Company_logo.svg",
  "AJAX": "https://upload.wikimedia.org/wikipedia/commons/8/8c/AJAX_logo_by_gengns.svg",
  "API": "https://cdn-icons-png.flaticon.com/512/888/888879.png",
  // --- From your graph ---
  "HTML": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg",
  "CSS": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg",
  "jQuery": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jquery/jquery-original.svg",
  "REST API": "https://cdn-icons-png.flaticon.com/512/1036/1036631.png",
  "Flash MySQL": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original.svg",
  "Bitrix 24": "https://upload.wikimedia.org/wikipedia/commons/4/4b/Bitrix_24_logo.svg",
  "ORM": "https://cdn-icons-png.flaticon.com/512/1087/1087815.png", // универсальная
  "PHPUnit": "https://upload.wikimedia.org/wikipedia/commons/7/74/PHPUnit_Logo.png",
  "LMS": "https://cdn-icons-png.flaticon.com/512/2659/2659360.png", // условная
  "LMS Moodle": "https://oksei.ru/public/img/moodle.png",
  "PHP5": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/php/php-original.svg",
  "Memcached": "https://upload.wikimedia.org/wikipedia/en/0/05/Memcached.svg",
  "Symfony": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/symfony/symfony-original.svg",
  "Yii": "https://www.yiiframework.com/image/design/logo/yii3_full.svg",
  "HTML/CSS": "https://cdn-icons-png.flaticon.com/512/732/732190.png",
  "ООП": "https://cdn-icons-png.flaticon.com/512/906/906175.png", // условно, как general programming
  "XDebug": "https://xdebug.org/images/logos/xdebug.svg",
  "Agile Project Management": "https://cdn-icons-png.flaticon.com/512/4764/4764825.png",
  "PHP Developer": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/php/php-original.svg",
  "C# Developer": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/csharp/csharp-original.svg",
  "Java Developer": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg",

  // --- Категории ---
  "programming_languages": "https://cdn-icons-png.flaticon.com/512/2721/2721297.png",
  "frameworks": "https://cdn-icons-png.flaticon.com/512/2721/2721297.png",
  "web_frameworks": "https://cdn-icons-png.flaticon.com/512/2721/2721297.png",
  "databases": "https://cdn-icons-png.flaticon.com/512/2991/2991108.png",
  "tools": "https://cdn-icons-png.flaticon.com/512/2620/2620611.png",
  "other": "https://cdn-icons-png.flaticon.com/512/2620/2620611.png",

  // --- Технологии ---
  "Java EE": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg",
  "Groovy": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/groovy/groovy-original.svg",
  "Spring Framework": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/spring/spring-original.svg",
  "Vaadin": "https://cdn.worldvectorlogo.com/logos/vaadin.svg",
  "Spring Data": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/spring/spring-original.svg",
  "Spring Cloud": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/spring/spring-original.svg",
  "Oracle": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/oracle/oracle-original.svg",
  "Hibernate ORM": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/hibernate/hibernate-original.svg",
  "Kafka": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/apachekafka/apachekafka-original.svg",
  "Gradle": "https://keramiozsoy.wordpress.com/wp-content/uploads/2018/05/gradle.png",
  "Apache Maven": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/maven/maven-original.svg",
  "Apache Zookeeper": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/apache/apache-original.svg",
  "Hazelcast": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/hazelcast/hazelcast-original.svg",
  "OpenShift": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/openshift/openshift-original.svg",
  "Camunda": "https://cdn.worldvectorlogo.com/logos/camunda.svg",
  "BPMN": "https://cdn-icons-png.flaticon.com/512/906/906175.png",
  "Английский язык": "https://cdn-icons-png.flaticon.com/512/197/197374.png",
  "Английский — A1 — Начальный": "https://cdn-icons-png.flaticon.com/512/197/197374.png",
  "Mustache": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mustache/mustache-original.svg",
  // --- Технологии и термины ---
  "С#": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/csharp/csharp-original.svg", // русская версия
  "MS SQL": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/microsoftsqlserver/microsoftsqlserver-plain.svg",
  "ASP.NET": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/dot-net/dot-net-original.svg",
  "Разработка ПО": "https://cdn-icons-png.flaticon.com/512/1055/1055687.png",
  "СУБД": "https://cdn-icons-png.flaticon.com/512/337/337946.png",
   // --- Soft Skills / Прочее ---
   "Стремление к профессиональному росту": "https://cdn-icons-png.flaticon.com/512/3135/3135715.png",
   "Системность": "https://cdn-icons-png.flaticon.com/512/3208/3208723.png",
   "Внимательность, ответственность": "https://cdn-icons-png.flaticon.com/512/2965/2965567.png",
   "OpenAPI": "https://avatars.githubusercontent.com/u/16343502?s=280&v=4",
  "symphony": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/symfony/symfony-original.svg",
  "Бизнес-аналитик": "https://cdn-icons-png.flaticon.com/512/3177/3177361.png",

  // --- Категории ---
  "технологии": "https://cdn-icons-png.flaticon.com/512/2721/2721297.png",
  "методологии и стандарты": "https://cdn-icons-png.flaticon.com/512/10712/10712253.png",
  "навыки": "https://cdn-icons-png.flaticon.com/512/4381/4381495.png",

  // --- Технологии / Программы ---
  "MS Excel": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/excel/excel-original.svg",
  "Atlassian Confluence": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/confluence/confluence-original.svg",
  "MS PowerPoint": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/powerpoint/powerpoint-original.svg",
  "ARIS": "https://www.softwareag.com/etc.clientlibs/softwareag/clientlibs/clientlib-site/resources/images/brand/software-ag-logo.svg", // условно
  "APS": "https://cdn-icons-png.flaticon.com/512/2936/2936958.png", // placeholder
  "amoCRM": "https://www.amocrm.com/assets/images/logo.svg",
  "Sensei": "https://cdn-icons-png.flaticon.com/512/2917/2917995.png", // placeholder
  "Miro": "https://cdn.worldvectorlogo.com/logos/miro-2.svg",


  // --- Навыки / Soft skills / Подходы ---
  "Atlassian Jira": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jira/jira-original.svg",
  "Удаленная работа": "https://cdn-icons-png.flaticon.com/512/4285/4285369.png",
  "ERP": "https://cdn-icons-png.flaticon.com/512/2790/2790494.png",
  "Data Analysis": "https://cdn-icons-png.flaticon.com/512/7062/7062421.png",
  "Английский — A2 — Элементарный": "https://cdn-icons-png.flaticon.com/512/197/197374.png",
  "Разработка технических заданий": "https://cdn-icons-png.flaticon.com/512/3580/3580420.png",
  "Работа в команде": "https://cdn-icons-png.flaticon.com/512/2910/2910791.png",
  "Работа в условиях многозадачности": "https://cdn-icons-png.flaticon.com/512/3107/3107242.png",
  "Постановка задач разработчикам": "https://cdn-icons-png.flaticon.com/512/5034/5034297.png",
  "Системный анализ": "https://cdn-icons-png.flaticon.com/512/3588/3588530.png",
  "Моделирование бизнес процессов": "https://cdn-icons-png.flaticon.com/512/1484/1484823.png",
  "Деловая коммуникация": "https://cdn-icons-png.flaticon.com/512/201/201613.png",
  "Оценка потребностей клиентов": "https://cdn-icons-png.flaticon.com/512/4814/4814985.png",
  "Маркетинговый анализ": "https://cdn-icons-png.flaticon.com/512/4149/4149643.png",
  "Системное мышление": "https://cdn-icons-png.flaticon.com/512/4095/4095854.png",
  "Работа с большим объемом информации": "https://cdn-icons-png.flaticon.com/512/3523/3523063.png",
  "Управление командой": "https://cdn-icons-png.flaticon.com/512/4783/4783610.png",
  "Техническое сопровождение": "https://cdn-icons-png.flaticon.com/512/10704/10704015.png",
  "Грамотность": "https://cdn-icons-png.flaticon.com/512/2885/2885313.png",
  "Цифровизация": "https://cdn-icons-png.flaticon.com/512/10607/10607593.png",
  "ТОиР": "https://cdn-icons-png.flaticon.com/512/6781/6781797.png",
  "Оптимизация бизнес-процессов": "https://cdn-icons-png.flaticon.com/512/10712/10712460.png",
  "Деловая переписка": "https://cdn-icons-png.flaticon.com/512/1238/1238807.png",
  "ГОСТ 34": "https://cdn-icons-png.flaticon.com/512/3771/3771500.png",
  "РД 50-34": "https://cdn-icons-png.flaticon.com/512/3771/3771500.png",
  "Управление производством": "https://cdn-icons-png.flaticon.com/512/10711/10711227.png",
  "Реинжиниринг бизнес-процессов": "https://cdn-icons-png.flaticon.com/512/10368/10368439.png",
  "Бизнес-моделирование": "https://cdn-icons-png.flaticon.com/512/1122/1122339.png",
  "Описание бизнес-процессов": "https://cdn-icons-png.flaticon.com/512/10710/10710700.png",
  "Маркетинговый аналитик": "https://cdn-icons-png.flaticon.com/512/3774/3774299.png",
  // --- Категории ---
  "языки программирования": "https://cdn-icons-png.flaticon.com/512/2721/2721297.png",
  // --- Технологии ---
  "Google Analytics": "https://upload.wikimedia.org/wikipedia/commons/7/7c/Google_Analytics_Logo.png",
  "Яндекс.Метрика": "https://upload.wikimedia.org/wikipedia/commons/1/11/Yandex_Metrica_logo_icon.svg",
  // --- Навыки и soft skills ---
  "Английский — B1 — Средний": "https://cdn-icons-png.flaticon.com/512/197/197374.png",
  "Английский — B2 — Средне-продвинутый": "https://cdn-icons-png.flaticon.com/512/197/197374.png",
  "Английский язык (Upper-Intermediate)": "https://cdn-icons-png.flaticon.com/512/197/197374.png",
  "Математическая статистика": "https://cdn-icons-png.flaticon.com/512/2140/2140460.png",
  "Сбор и анализ информации": "https://cdn-icons-png.flaticon.com/512/951/951282.png",
  "Аналитика": "https://cdn-icons-png.flaticon.com/512/1584/1584945.png",
  "Работа с базами данных": "https://cdn-icons-png.flaticon.com/512/10717/10717179.png",
  "Аналитические исследования": "https://cdn-icons-png.flaticon.com/512/9487/9487770.png",
  "Анализ трафика": "https://cdn-icons-png.flaticon.com/512/838/838321.png",
  "Gamedev": "https://cdn-icons-png.flaticon.com/512/971/971823.png",
  "Calltouch": "https://upload.wikimedia.org/wikipedia/commons/7/70/Calltouch_logo.svg",
  "Веб-аналитика": "https://cdn-icons-png.flaticon.com/512/1048/1048940.png",
  "WEB аналитика": "https://cdn-icons-png.flaticon.com/512/1048/1048940.png",
  "Подготовка презентаций": "https://cdn-icons-png.flaticon.com/512/2917/2917995.png",
  "Визуализация данных": "https://cdn-icons-png.flaticon.com/512/4149/4149688.png",
  "A/B тесты": "https://cdn-icons-png.flaticon.com/512/5953/5953766.png",
  "Разработка маркетинговой стратегии": "https://cdn-icons-png.flaticon.com/512/1055/1055687.png",
  "Internet Marketing": "https://cdn-icons-png.flaticon.com/512/428/428001.png",
  "Интернет маркетинг": "https://cdn-icons-png.flaticon.com/512/428/428001.png",
  "Интернет-реклама": "https://cdn-icons-png.flaticon.com/512/1048/1048927.png",
  "SEO": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/seo/seo-original.svg",
  "Ad Hoc Analysis": "https://cdn-icons-png.flaticon.com/512/1233/1233949.png",
  "Креативность": "https://cdn-icons-png.flaticon.com/512/427/427735.png",
  "Прогнозирование": "https://cdn-icons-png.flaticon.com/512/2910/2910825.png",
  "Маркетинговые исследования": "https://cdn-icons-png.flaticon.com/512/4149/4149651.png",

  // --- Профессии ---
  "iOS Developer": "https://cdn-icons-png.flaticon.com/512/731/731985.png",
  "Oracle Developer": "https://cdn-icons-png.flaticon.com/512/5968/5968342.png",
  "C++ Developer": "https://cdn-icons-png.flaticon.com/512/6132/6132222.png",

  // --- Технологии и инструменты ---
  "1С: Бухгалтерия": "https://upload.wikimedia.org/wikipedia/commons/3/3f/1C_Company_logo.svg",
  "ERP-системы на базе 1С": "https://upload.wikimedia.org/wikipedia/commons/3/3f/1C_Company_logo.svg",
  "Borland C++": "https://upload.wikimedia.org/wikipedia/commons/3/3f/Borland_C%2B%2B_Logo.png",
  "Lua": "https://www.lua.org/images/lua-logo.gif",
  "CMake": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/cmake/cmake-original.svg",
  "Mathcad": "https://cdn.worldvectorlogo.com/logos/ptc-mathcad-logo.svg",
  "Objective-C": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/objectivec/objectivec-plain.svg",
  "Intel C++": "https://upload.wikimedia.org/wikipedia/commons/1/1e/Intel_logo.svg",
  "Bash": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/bash/bash-original.svg",
  "ETL": "https://cdn-icons-png.flaticon.com/512/4149/4149643.png",
  "Oracle PL/SQL.": "https://cdn-icons-png.flaticon.com/512/5968/5968342.png",
  "Oracle PL/SQL": "https://cdn-icons-png.flaticon.com/512/5968/5968342.png",
  "DWH": "https://cdn-icons-png.flaticon.com/512/4149/4149643.png",
  "Teradata": "https://upload.wikimedia.org/wikipedia/commons/6/6b/Teradata_logo.svg",
  "PostgreSQL PL/pgSQL": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg",
  "UDP": "https://cdn-icons-png.flaticon.com/512/4248/4248443.png",
  "CAD": "https://cdn-icons-png.flaticon.com/512/4149/4149643.png",
  "CocoaPods": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/cocoapods/cocoapods-plain.svg",
  "Unit Testing": "https://cdn-icons-png.flaticon.com/512/4149/4149643.png",
  "OpenGL": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/opengl/opengl-original.svg",
  "SVN": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/subversion/subversion-original.svg",
  "База данных: Oracle": "https://user-images.githubusercontent.com/25181517/117208736-bdedc080-adf5-11eb-912f-61c7d43705f6.png",
  "С++": "https://repository-images.githubusercontent.com/327470624/2d865200-6bf1-11eb-9d0e-2a488615d6ec",
  "Bitrix": "https://upload.wikimedia.org/wikipedia/ru/thumb/5/51/1c_bitrix_logo.svg/1200px-1c_bitrix_logo.svg.png",

  // --- Библиотеки и фреймворки ---
  "Qt": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/qt/qt-original.svg",
  "WinAPI": "https://cdn-icons-png.flaticon.com/512/4248/4248443.png",
  "Boost": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/boost/boost-original.svg",
  "Multithread Programming": "https://cdn-icons-png.flaticon.com/512/4149/4149643.png",
  "MFC": "https://cdn-icons-png.flaticon.com/512/4149/4149643.png",
  "C/C++": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/cplusplus/cplusplus-original.svg",
  "STL": "https://cdn-icons-png.flaticon.com/512/4149/4149643.png",
  "Low latency": "https://cdn-icons-png.flaticon.com/512/4149/4149643.png",
  "TCP/IP":"https://media.istockphoto.com/vectors/vector-illustration-icon-for-the-tcpip-protocol-vector-id1148291197?k=6&m=1148291197&s=612x612&w=0&h=u_ePwTLiWiD3idPyc-Oq89eqSMXhnZOAnH96L5nVnNM=",
  "Combine": "https://developer.apple.com/assets/elements/icons/combine/combine-96x96_2x.png",
  "SwiftUI": "https://developer.apple.com/assets/elements/icons/swiftui/swiftui-96x96_2x.png",
  "UIKit": "https://developer.apple.com/assets/elements/icons/uikit/uikit-96x96_2x.png",

  "libraries": "https://images-eds-ssl.xboxlive.com/image?url=4rt9.lXDC4H_93laV1_eHHFT949fUipzkiFOBH3fAiZZUCdYojwUyX2aTonS1aIwMrx6NUIsHfUHSLzjGJFxxqXmpzzP4fEmA4GGS.i8b4hgtapO3T1gMM2UlnINYS3RmSH5sLbtRrA2khCtm6zdEBzrIytCVN5CyRAJaUoPvic-&format=source",

  // --- Soft skills / Навыки ---
  "Organizational skills": "https://cdn-icons-png.flaticon.com/512/2991/2991148.png",
  "Организаторские навыки": "https://cdn-icons-png.flaticon.com/512/2991/2991148.png",
  "Ориентация на результат": "https://cdn-icons-png.flaticon.com/512/3176/3176295.png",
  "Presentation skills": "https://cdn-icons-png.flaticon.com/512/2917/2917995.png",
  "Лидерские качества": "https://cdn-icons-png.flaticon.com/512/3135/3135789.png",
  "Project management": "https://cdn-icons-png.flaticon.com/512/1055/1055687.png",

  // --- UI/UX и веб ---
  "UX": "https://cdn-icons-png.flaticon.com/512/888/888853.png",
  "UI": "https://cdn-icons-png.flaticon.com/512/888/888841.png",
  "Веб-программирование": "https://cdn-icons-png.flaticon.com/512/1006/1006771.png",
  "WebSocket": "https://cdn-icons-png.flaticon.com/512/609/609803.png",

  // --- Разработка ПО и архитектура ---
  "MS Visual C++": "https://upload.wikimedia.org/wikipedia/commons/1/13/Visual_Studio_Icon_2022.svg",
  "Product Management": "https://cdn-icons-png.flaticon.com/512/1686/1686300.png",
  "SOLID": "https://cdn-icons-png.flaticon.com/512/2882/2882180.png",
  "SOA": "https://cdn-icons-png.flaticon.com/512/5968/5968292.png", // Service-based icon
  "Conan": "https://conan.io/img/conan_logo.svg", // C/C++ package manager

  // --- Образование и обучение ---
  "E-Learning": "https://cdn-icons-png.flaticon.com/512/2942/2942809.png",
  "ASO": "https://cdn-icons-png.flaticon.com/512/875/875610.png", // App Store Optimization (абстрактная)
  "Научная деятельность": "https://cdn-icons-png.flaticon.com/512/1055/1055687.png", // R&D icon

  // --- Робототехника ---
  "Разработка робототехники": "https://cdn-icons-png.flaticon.com/512/3523/3523063.png",
  "Проектный менеджмент": "https://cdn-icons-png.flaticon.com/512/1055/1055687.png",

  "technologies": "https://cdn-icons-png.flaticon.com/512/2620/2620611.png",

  // --- Технологии ---
  "Xsd": "https://cdn-icons-png.flaticon.com/512/337/337946.png", // XML schema – универсальная
  "XML/Xslt": "https://cdn-icons-png.flaticon.com/512/136/136526.png",

  // --- Категория ---
  "skills": "https://cdn-icons-png.flaticon.com/512/4381/4381495.png",

  // --- Навыки и качества ---
  "Готов к переезду": "https://cdn-icons-png.flaticon.com/512/126/126122.png",
  "Готовность к командировкам": "https://cdn-icons-png.flaticon.com/512/1046/1046777.png",
  "Уверенный пользователь ПК": "https://cdn-icons-png.flaticon.com/512/1006/1006544.png",
  "Ответственный подход к работе": "https://cdn-icons-png.flaticon.com/512/190/190411.png",
  "Эффективность": "https://cdn-icons-png.flaticon.com/512/4341/4341084.png",
  "Логика": "https://cdn-icons-png.flaticon.com/512/3443/3443791.png",

  // --- Тестирование / QA ---
  "Регрессионное тестирование": "https://cdn-icons-png.flaticon.com/512/2720/2720550.png",
  "Проведение тестирований": "https://cdn-icons-png.flaticon.com/512/2700/2700397.png",
  "Тестирование пользовательского интерфейса": "https://cdn-icons-png.flaticon.com/512/3422/3422791.png",
  "Тестирование интеграций между системами": "https://cdn-icons-png.flaticon.com/512/1086/1086741.png",
  "Функциональное тестирование": "https://cdn-icons-png.flaticon.com/512/3281/3281298.png",
  "автотест": "https://cdn-icons-png.flaticon.com/512/3081/3081648.png",
  "Vanessa-Automation": "https://avatars.githubusercontent.com/u/37618461?s=200&v=4", // официальный логотип GitHub

  // --- 1С-ориентированные задачи ---
  "Создание конфигурации 1С": "https://upload.wikimedia.org/wikipedia/commons/3/3f/1C_Company_logo.svg",
  "Обновление конфигурации 1С": "https://upload.wikimedia.org/wikipedia/commons/3/3f/1C_Company_logo.svg",
  "Знание 1С Предприятие": "https://upload.wikimedia.org/wikipedia/commons/3/3f/1C_Company_logo.svg",
  "Знание программы 1С": "https://upload.wikimedia.org/wikipedia/commons/3/3f/1C_Company_logo.svg",
  "Разработка расширений": "https://cdn-icons-png.flaticon.com/512/2921/2921222.png",

  // --- Финансовые действия (1С-бухгалтерия) ---
  "приходные и расходные операции": "https://cdn-icons-png.flaticon.com/512/1029/1029183.png"

  };

  const normalizedKeyMap: Record<string, string> = Object.keys(iconMap).reduce((acc, key) => {
    acc[key.toLowerCase()] = key;
    return acc;
  }, {} as Record<string, string>);
  
  export const getIconUrl = (label: string): string => {
    const normalizedKey = normalizedKeyMap[label.toLowerCase()];
    return iconMap[normalizedKey] || "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/devicon/devicon-original.svg";
  };